-- Scenario 3: Student Hostel Room Allocation

DROP SCHEMA IF EXISTS student_hostel_room_allocation CASCADE;
CREATE SCHEMA student_hostel_room_allocation;
SET search_path TO student_hostel_room_allocation, public;

-- Task 1: Create tables and insert initial records
CREATE TABLE hostel_rooms (
    room_id integer PRIMARY KEY,
    room_number text NOT NULL,
    available_spaces integer NOT NULL CHECK (available_spaces >= 0)
);

CREATE TABLE allocations (
    allocation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id integer NOT NULL REFERENCES hostel_rooms(room_id),
    student_number text NOT NULL CHECK (length(trim(student_number)) > 0),
    status text NOT NULL CHECK (status IN ('ALLOCATED', 'COMPLETED'))
);

INSERT INTO hostel_rooms (room_id, room_number, available_spaces)
VALUES 
    (1, 'Kabwe - Room 15', 4),
    (2, 'kabwe - Room 23', 1),
    (3, 'Mweru - Room 17', 3),
	(4, 'Kariba - Room 20', 0),
	(5, 'kariba - Room 25', 0);

-- Task 2: IF ELSIF ELSE decision control structure
DO $$
DECLARE
    v_spaces integer;
BEGIN
    SELECT available_spaces INTO v_spaces FROM hostel_rooms WHERE room_id = 2;
    IF v_spaces = 0 THEN
        RAISE NOTICE 'Room is full';
    ELSIF v_spaces = 1 THEN
        RAISE NOTICE 'Room has one space left';
    ELSE
        RAISE NOTICE 'Room has several spaces available: % spaces', v_spaces;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Task 3: WHILE loop and numeric FOR loop
DO $$
DECLARE
    v_day integer := 1;
BEGIN
    WHILE v_day <= 3 LOOP
        RAISE NOTICE 'Hostel inspection day %', v_day;
        v_day := v_day + 1;
    END LOOP;

    FOR v_check IN 1..3 LOOP
        RAISE NOTICE 'Room check number %', v_check;
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- Task 4: Stored procedure for allocating hostel rooms
CREATE OR REPLACE PROCEDURE allocate_room(
    p_room_id integer,
    p_student_number text
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_spaces integer;
    v_alloc_id integer;
BEGIN
    IF p_student_number IS NULL OR trim(p_student_number) = '' THEN
        RAISE EXCEPTION 'Student number cannot be blank' USING ERRCODE = '22023';
    END IF;

    SELECT available_spaces INTO v_spaces
    FROM hostel_rooms WHERE room_id = p_room_id FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'Room % does not exist', p_room_id;
        RETURN;
    ELSIF v_spaces < 1 THEN
        RAISE NOTICE 'Room % is full', p_room_id;
        RETURN;
    END IF;

    UPDATE hostel_rooms SET available_spaces = available_spaces - 1 WHERE room_id = p_room_id;

    INSERT INTO allocations (room_id, student_number, status)
    VALUES (p_room_id, p_student_number, 'ALLOCATED')
    RETURNING allocation_id INTO v_alloc_id;

    RAISE NOTICE 'Allocation % created for student %', v_alloc_id, p_student_number;
END;
$$;

-- Task 5: Execute allocate_room calls and verify state
CALL allocate_room(1, '202402427');
CALL allocate_room(2, '202402728');
CALL allocate_room(3, '202402829');


SELECT * FROM hostel_rooms ORDER BY room_id;
SELECT * FROM allocations ORDER BY allocation_id;

-- Task 6: Stored procedure for student check-out
CREATE OR REPLACE PROCEDURE check_out(p_allocation_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_room_id integer;
BEGIN
    SELECT room_id INTO v_room_id
    FROM allocations WHERE allocation_id = p_allocation_id AND status = 'ALLOCATED' FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active allocation with ID %', p_allocation_id;
        RETURN;
    END IF;

    UPDATE allocations SET status = 'COMPLETED' WHERE allocation_id = p_allocation_id;
    UPDATE hostel_rooms SET available_spaces = available_spaces + 1 WHERE room_id = v_room_id;

    RAISE NOTICE 'Allocation % checked out; space freed in room %', p_allocation_id, v_room_id;
END;
$$;

CALL check_out(1);
CALL check_out(1);

-- Task 7: Explicit cursor for nearly full rooms
DO $$
DECLARE
    v_rec RECORD;
    c_rooms CURSOR FOR
        SELECT room_number, available_spaces FROM hostel_rooms WHERE available_spaces <= 1 ORDER BY room_id;
BEGIN
    OPEN c_rooms;
    LOOP
        FETCH c_rooms INTO v_rec;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Full/Nearly full room: % (% spaces left)', v_rec.room_number, v_rec.available_spaces;
    END LOOP;
    CLOSE c_rooms;
END;
$$ LANGUAGE plpgsql;

-- Task 8: Exception handling block
DO $$
BEGIN
    CALL allocate_room(1, '   ');
EXCEPTION WHEN invalid_parameter_value THEN
    RAISE NOTICE 'Handled error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;

-- Task 9: Final state verification
SELECT * FROM hostel_rooms ORDER BY room_id;
SELECT * FROM allocations ORDER BY allocation_id;