-- Scenario 1: University Library Book Loans

DROP SCHEMA IF EXISTS university_library_book_loans CASCADE;
CREATE SCHEMA university_library_book_loans;
SET search_path TO university_library_book_loans, public;

-- Task 1: Create tables and insert initial records
CREATE TABLE books (
    book_id integer PRIMARY KEY,
    title text NOT NULL,
    available_copies integer NOT NULL CHECK (available_copies >= 0)
);

CREATE TABLE book_loans (
    loan_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id integer NOT NULL REFERENCES books(book_id),
    student_number integer NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    status text NOT NULL CHECK (status IN ('ACTIVE', 'RETURNED'))
);

INSERT INTO books (book_id, title, available_copies)
VALUES 
    (1, 'Advanced database', 25),
    (2, 'System design analysis', 10),
    (3, 'Business Management', 24),
	(4, 'App development', 32),
	(5, 'Cybersecurity principles', 42);

-- Task 2: IF ELSIF ELSE decision control structure
DO $$
DECLARE
    v_copies integer;
BEGIN
    SELECT available_copies INTO v_copies FROM books WHERE book_id = 2;
    IF v_copies = 0 THEN
        RAISE NOTICE 'Book is unavailable';
    ELSIF v_copies <= 5 THEN
        RAISE NOTICE 'Book stock low: % copies remaining', v_copies;
    ELSE
        RAISE NOTICE 'Book sufficiently stocked: % copies remaining', v_copies;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Task 3: WHILE loop and numeric FOR loop
DO $$
DECLARE
    v_reminder integer := 1;
BEGIN
    WHILE v_reminder <= 3 LOOP
        RAISE NOTICE 'Overdue reminder %', v_reminder;
        v_reminder := v_reminder + 1;
    END LOOP;

    FOR v_shelf IN 1..3 LOOP
        RAISE NOTICE 'Library shelf number %', v_shelf;
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- Task 4: Stored procedure for borrowing books
CREATE OR REPLACE PROCEDURE borrow_book(
    p_book_id integer,
    p_student_number integer,
    p_quantity integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available integer;
    v_loan_id integer;
BEGIN
    IF p_quantity <= 0 THEN
        RAISE EXCEPTION 'Quantity must be positive' USING ERRCODE = '22023';
    END IF;

    SELECT available_copies INTO v_available
    FROM books WHERE book_id = p_book_id FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'Book % does not exist', p_book_id;
        RETURN;
    ELSIF v_available < p_quantity THEN
        RAISE NOTICE 'Insufficient copies: only % available', v_available;
        RETURN;
    END IF;

    UPDATE books SET available_copies = available_copies - p_quantity WHERE book_id = p_book_id;

    INSERT INTO book_loans (book_id, student_number, quantity, status)
    VALUES (p_book_id, p_student_number, p_quantity, 'ACTIVE')
    RETURNING loan_id INTO v_loan_id;

    RAISE NOTICE 'Loan % recorded for student %', v_loan_id, p_student_number;
END;
$$;

-- Task 5: Execute borrow_book calls and verify state
CALL borrow_book(1, '202402427', 2);
CALL borrow_book(2, '202405342', 1);
CALL borrow_book(2, '202408941', 11);
SELECT * FROM books ORDER BY book_id;
SELECT * FROM book_loans ORDER BY loan_id;

-- Task 6: Stored procedure for returning books
CREATE OR REPLACE PROCEDURE return_book(p_loan_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_book_id integer;
    v_quantity integer;
BEGIN
    SELECT book_id, quantity INTO v_book_id, v_quantity
    FROM book_loans WHERE loan_id = p_loan_id AND status = 'ACTIVE' FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active loan found for loan ID %', p_loan_id;
        RETURN;
    END IF;

    UPDATE book_loans SET status = 'RETURNED' WHERE loan_id = p_loan_id;
    UPDATE books SET available_copies = available_copies + v_quantity WHERE book_id = v_book_id;

    RAISE NOTICE 'Loan % returned; % copies restored', p_loan_id, v_quantity;
END;
$$;

CALL return_book(1);
CALL return_book(1);

-- Task 7: Explicit cursor for low stock reporting
DO $$
DECLARE
    v_rec RECORD;
    c_low CURSOR FOR
        SELECT title, available_copies FROM books WHERE available_copies <= 2 ORDER BY book_id;
BEGIN
    OPEN c_low;
    LOOP
        FETCH c_low INTO v_rec;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Low stock book: % (% copies remaining)', v_rec.title, v_rec.available_copies;
    END LOOP;
    CLOSE c_low;
END;
$$ LANGUAGE plpgsql;

-- Task 8: Exception handling block
DO $$
BEGIN
    CALL borrow_book(3, '202402427', 5);
EXCEPTION WHEN invalid_parameter_value THEN
    RAISE NOTICE 'Handled invalid quantity error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;

-- Task 9: Final state verification
SELECT * FROM books ORDER BY book_id;
SELECT * FROM book_loans ORDER BY loan_id;