-- Scenario 2: Computer Laboratory Reservations

DROP SCHEMA IF EXISTS computer_laboratory_reservations CASCADE;
CREATE SCHEMA computer_laboratory_reservations;
SET search_path TO computer_laboratory_reservations, public;

-- Task 1: Create tables and insert initial records
CREATE TABLE lab_sessions (
    session_id integer PRIMARY KEY,
    session_name text NOT NULL,
    available_workstations integer NOT NULL CHECK (available_workstations >= 0)
);

CREATE TABLE reservations (
    reservation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL REFERENCES lab_sessions(session_id),
    lecturer_name text NOT NULL,
    workstations_reserved integer NOT NULL CHECK (workstations_reserved > 0),
    status text NOT NULL CHECK (status IN ('RESERVED', 'CANCELLED'))
);

INSERT INTO lab_sessions (session_id, session_name, available_workstations)
VALUES 
    (1, 'ICT371 07:00hrs Session', 30),
    (2, 'ICT341 09:00hrs Session', 5),
    (3, 'ICT351 11:00hrs Session', 3),
	(4, 'ICT381 13:00hrs Session', 7),
	(5, 'ICT361 15:00hrs Session', 9),
	(6, 'ICT391 17:00hrs Session', 6);

-- Task 2: IF ELSIF ELSE decision control structure
DO $$
DECLARE
    v_available integer;
BEGIN
    SELECT available_workstations INTO v_available FROM lab_sessions WHERE session_id = 2;
    IF v_available = 0 THEN
        RAISE NOTICE 'Session is full';
    ELSIF v_available <= 5 THEN
        RAISE NOTICE 'Session is nearly full: % workstations left', v_available;
    ELSE
        RAISE NOTICE 'Session has enough workstations: % available', v_available;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Task 3: WHILE loop and numeric FOR loop
DO $$
DECLARE
    v_rem integer := 1;
BEGIN
    WHILE v_rem <= 3 LOOP
        RAISE NOTICE 'Preparation reminder %', v_rem;
        v_rem := v_rem + 1;
    END LOOP;

    FOR v_chk IN 1..3 LOOP
        RAISE NOTICE 'Workstation check number %', v_chk;
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- Task 4: Stored procedure for reserving workstations
CREATE OR REPLACE PROCEDURE reserve_workstations(
    p_session_id integer,
    p_lecturer text,
    p_workstations integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_available integer;
    v_res_id integer;
BEGIN
    IF p_workstations <= 0 THEN
        RAISE EXCEPTION 'Workstations requested must be positive' USING ERRCODE = '22023';
    END IF;

    SELECT available_workstations INTO v_available
    FROM lab_sessions WHERE session_id = p_session_id FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'Session % does not exist', p_session_id;
        RETURN;
    ELSIF v_available < p_workstations THEN
        RAISE NOTICE 'Exceeds capacity: only % workstations available', v_available;
        RETURN;
    END IF;

    UPDATE lab_sessions SET available_workstations = available_workstations - p_workstations WHERE session_id = p_session_id;

    INSERT INTO reservations (session_id, lecturer_name, workstations_reserved, status)
    VALUES (p_session_id, p_lecturer, p_workstations, 'RESERVED')
    RETURNING reservation_id INTO v_res_id;

    RAISE NOTICE 'Reservation % recorded for Lecturer %', v_res_id, p_lecturer;
END;
$$;

-- Task 5: Execute reserve_workstations calls and verify state
CALL reserve_workstations(1, 'Mr KALUBA ', 10);
CALL reserve_workstations(2, 'MR BWALYA', 3);
CALL reserve_workstations(2, 'MR NYIRENDA', 15);

SELECT * FROM lab_sessions ORDER BY session_id;
SELECT * FROM reservations ORDER BY reservation_id;

-- Task 6: Stored procedure for cancelling reservations
CREATE OR REPLACE PROCEDURE cancel_reservation(p_reservation_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_session_id integer;
    v_count integer;
BEGIN
    SELECT session_id, workstations_reserved INTO v_session_id, v_count
    FROM reservations WHERE reservation_id = p_reservation_id AND status = 'RESERVED' FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active reservation with ID %', p_reservation_id;
        RETURN;
    END IF;

    UPDATE reservations SET status = 'CANCELLED' WHERE reservation_id = p_reservation_id;
    UPDATE lab_sessions SET available_workstations = available_workstations + v_count WHERE session_id = v_session_id;

    RAISE NOTICE 'Reservation % cancelled; % workstations released', p_reservation_id, v_count;
END;
$$;

CALL cancel_reservation(1);
CALL cancel_reservation(1);

-- Task 7: Explicit cursor for low capacity sessions
DO $$
DECLARE
    v_rec RECORD;
    c_low CURSOR FOR
        SELECT session_name, available_workstations FROM lab_sessions WHERE available_workstations <= 5 ORDER BY session_id;
BEGIN
    OPEN c_low;
    LOOP
        FETCH c_low INTO v_rec;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Low availability: % (% workstations remaining)', v_rec.session_name, v_rec.available_workstations;
    END LOOP;
    CLOSE c_low;
END;
$$ LANGUAGE plpgsql;

-- Task 8: Exception handling block
DO $$
BEGIN
    CALL reserve_workstations(1, 'MR KALUBA', 0);
EXCEPTION WHEN invalid_parameter_value THEN
    RAISE NOTICE 'Handled error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;

-- Task 9: Final state verification
SELECT * FROM lab_sessions ORDER BY session_id;
SELECT * FROM reservations ORDER BY reservation_id;
