-- Scenario 4: Campus Clinic Medicine Dispensing

DROP SCHEMA IF EXISTS campus_clinic_medicine_dispensing CASCADE;
CREATE SCHEMA campus_clinic_medicine_dispensing;
SET search_path TO campus_clinic_medicine_dispensing, public;

-- Task 1: Create tables and insert initial records
CREATE TABLE medicines (
    medicine_id integer PRIMARY KEY,
    medicine_name text NOT NULL,
    stock_quantity integer NOT NULL CHECK (stock_quantity >= 0)
);

CREATE TABLE dispensing_records (
    record_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_id integer NOT NULL REFERENCES medicines(medicine_id),
    student_number text NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    status text NOT NULL CHECK (status IN ('DISPENSED', 'REVERSED'))
);

INSERT INTO medicines (medicine_id, medicine_name, stock_quantity)
VALUES 
    (1, 'Antacid 500mg', 50),
    (2, 'Amoxicillin 250mg', 5),
    (3, 'coughsyrup 400mg', 0),
	(4, 'Panadol 200mg', 9),
	(5, 'Vitamin c 100mg', 49);
	

-- Task 2: IF ELSIF ELSE decision control structure
DO $$
DECLARE
    v_stock integer;
BEGIN
    SELECT stock_quantity INTO v_stock FROM medicines WHERE medicine_id = 2;
    IF v_stock = 0 THEN
        RAISE NOTICE 'Medicine is out of stock';
    ELSIF v_stock <= 10 THEN
        RAISE NOTICE 'Medicine low on stock: % remaining', v_stock;
    ELSE
        RAISE NOTICE 'Medicine sufficiently stocked: % remaining', v_stock;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Task 3: WHILE loop and numeric FOR loop
DO $$
DECLARE
    v_day integer := 1;
BEGIN
    WHILE v_day <= 3 LOOP
        RAISE NOTICE 'Stock review day %', v_day;
        v_day := v_day + 1;
    END LOOP;

    FOR v_insp IN 1..3 LOOP
        RAISE NOTICE 'Shelf inspection %', v_insp;
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- Task 4: Stored procedure for dispensing medicine
CREATE OR REPLACE PROCEDURE dispense_medicine(
    p_medicine_id integer,
    p_student_number text,
    p_quantity integer
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_stock integer;
    v_rec_id integer;
BEGIN
    IF p_quantity <= 0 THEN
        RAISE EXCEPTION 'Dispensing quantity must be positive' USING ERRCODE = '22023';
    END IF;

    SELECT stock_quantity INTO v_stock
    FROM medicines WHERE medicine_id = p_medicine_id FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'Medicine % does not exist', p_medicine_id;
        RETURN;
    ELSIF v_stock < p_quantity THEN
        RAISE NOTICE 'Insufficient stock: only % available', v_stock;
        RETURN;
    END IF;

    UPDATE medicines SET stock_quantity = stock_quantity - p_quantity WHERE medicine_id = p_medicine_id;

    INSERT INTO dispensing_records (medicine_id, student_number, quantity, status)
    VALUES (p_medicine_id, p_student_number, p_quantity, 'DISPENSED')
    RETURNING record_id INTO v_rec_id;

    RAISE NOTICE 'Dispensing record % created for student %', v_rec_id, p_student_number;
END;
$$;

-- Task 5: Execute dispense_medicine calls and verify state
CALL dispense_medicine(1, '202402427', 10);
CALL dispense_medicine(2, '202402328', 2);
CALL dispense_medicine(3, '202402829', 5);

SELECT * FROM medicines ORDER BY medicine_id;
SELECT * FROM dispensing_records ORDER BY record_id;

-- Task 6: Stored procedure for reversing medicine dispensing
CREATE OR REPLACE PROCEDURE reverse_dispensing(p_record_id integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_med_id integer;
    v_qty integer;
BEGIN
    SELECT medicine_id, quantity INTO v_med_id, v_qty
    FROM dispensing_records WHERE record_id = p_record_id AND status = 'DISPENSED' FOR UPDATE;

    IF NOT FOUND THEN
        RAISE NOTICE 'No active dispensing record with ID %', p_record_id;
        RETURN;
    END IF;

    UPDATE dispensing_records SET status = 'REVERSED' WHERE record_id = p_record_id;
    UPDATE medicines SET stock_quantity = stock_quantity + v_qty WHERE medicine_id = v_med_id;

    RAISE NOTICE 'Record % reversed; % units restored', p_record_id, v_qty;
END;
$$;

CALL reverse_dispensing(1);
CALL reverse_dispensing(1);

-- Task 7: Explicit cursor for low stock medicines
DO $$
DECLARE
    v_rec RECORD;
    c_low CURSOR FOR
        SELECT medicine_name, stock_quantity FROM medicines WHERE stock_quantity <= 10 ORDER BY medicine_id;
BEGIN
    OPEN c_low;
    LOOP
        FETCH c_low INTO v_rec;
        EXIT WHEN NOT FOUND;
        RAISE NOTICE 'Low stock medicine: % (% units left)', v_rec.medicine_name, v_rec.stock_quantity;
    END LOOP;
    CLOSE c_low;
END;
$$ LANGUAGE plpgsql;

-- Task 8: Exception handling block
DO $$
BEGIN
    CALL dispense_medicine(1, '202402427', -5);
EXCEPTION WHEN invalid_parameter_value THEN
    RAISE NOTICE 'Handled error: %', SQLERRM;
END;
$$ LANGUAGE plpgsql;

-- Task 9: Final state verification
SELECT * FROM medicines ORDER BY medicine_id;
SELECT * FROM dispensing_records ORDER BY record_id;
